Repository SU-SWS/caw_profile, pull requests merged in 2021-08, with the labels that each got.

#7 CAW21-76 Build sweetener content type and views
  composer.json
  config/sync/core.base_field_override.node.caw_sweetener.promote.yml
  config/sync/core.entity_form_display.node.caw_sweetener.default.yml
  config/sync/core.entity_view_display.node.caw_sweetener.default.yml
  config/sync/core.entity_view_display.node.caw_sweetener.stanford_card.yml
  config/sync/core.entity_view_display.node.caw_sweetener.teaser.yml
  config/sync/core.entity_view_display.node.stanford_event.default.yml
  config/sync/core.entity_view_display.node.stanford_event_series.default.yml
  config/sync/core.entity_view_display.node.stanford_news.default.yml
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.entity_view_display.node.stanford_publication.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.caw_sweetener.su_sweet_avail.yml
  config/sync/field.field.node.caw_sweetener.su_sweet_components.yml
  config/sync/field.field.node.caw_sweetener.su_sweet_image.yml
  config/sync/field.field.node.caw_sweetener.su_sweet_info.yml
  config/sync/field.field.node.caw_sweetener.su_sweet_type.yml
  config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
  config/sync/field.storage.node.su_sweet_avail.yml
  config/sync/field.storage.node.su_sweet_components.yml
  config/sync/field.storage.node.su_sweet_image.yml
  config/sync/field.storage.node.su_sweet_info.yml
  config/sync/field.storage.node.su_sweet_type.yml
  config/sync/migrate_plus.migration.caw_sweeteners.yml
  config/sync/migrate_plus.migration.caw_sweeteners_components.yml
  config/sync/node.type.caw_sweetener.yml
  config/sync/page_manager.page_variant.event_series-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_events_list-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_events_past-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_person_list-layout_builder-0.yml
  config/sync/pathauto.pattern.caw_sweeteners.yml
  config/sync/rabbit_hole.behavior_settings.node_type_caw_sweetener.yml
  config/sync/taxonomy.vocabulary.caw_sweet_available.yml
  config/sync/taxonomy.vocabulary.caw_sweet_type.yml
  config/sync/user.role.contributor.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.caw_sweeteners.yml
  tests/codeception/acceptance/Content/SweetenersCest.php
Labels: size/l

#8 CAW21-79 Added career celebrations content type
  config/sync/auto_entitylabel.settings.node.caw_careers.yml
  config/sync/core.base_field_override.node.caw_careers.promote.yml
  config/sync/core.base_field_override.node.caw_careers.title.yml
  config/sync/core.entity_form_display.node.caw_careers.default.yml
  config/sync/core.entity_view_display.node.caw_careers.default.yml
  config/sync/core.entity_view_display.node.caw_careers.stanford_card.yml
  config/sync/field.field.node.caw_careers.su_careers_components.yml
  config/sync/field.field.node.caw_careers.su_careers_department.yml
  config/sync/field.field.node.caw_careers.su_careers_favorite_thing.yml
  config/sync/field.field.node.caw_careers.su_careers_fname.yml
  config/sync/field.field.node.caw_careers.su_careers_fun_fact.yml
  config/sync/field.field.node.caw_careers.su_careers_honored.yml
  config/sync/field.field.node.caw_careers.su_careers_image.yml
  config/sync/field.field.node.caw_careers.su_careers_job.yml
  config/sync/field.field.node.caw_careers.su_careers_legacy.yml
  config/sync/field.field.node.caw_careers.su_careers_lname.yml
  config/sync/field.field.node.caw_careers.su_careers_memory.yml
  config/sync/field.field.node.caw_careers.su_careers_proud_project.yml
  config/sync/field.field.node.caw_careers.su_careers_years.yml
  config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
  config/sync/field.storage.node.su_careers_components.yml
  config/sync/field.storage.node.su_careers_department.yml
  config/sync/field.storage.node.su_careers_favorite_thing.yml
  config/sync/field.storage.node.su_careers_fname.yml
  config/sync/field.storage.node.su_careers_fun_fact.yml
  config/sync/field.storage.node.su_careers_honored.yml
  config/sync/field.storage.node.su_careers_image.yml
  config/sync/field.storage.node.su_careers_job.yml
  config/sync/field.storage.node.su_careers_legacy.yml
  config/sync/field.storage.node.su_careers_lname.yml
  config/sync/field.storage.node.su_careers_memory.yml
  config/sync/field.storage.node.su_careers_proud_project.yml
  config/sync/field.storage.node.su_careers_years.yml
  config/sync/migrate_plus.migration.caw_careers.yml
  config/sync/migrate_plus.migration.caw_careers_components.yml
  config/sync/node.type.caw_careers.yml
  config/sync/pathauto.pattern.caw_careers.yml
  config/sync/rabbit_hole.behavior_settings.node_type_caw_careers.yml
  config/sync/taxonomy.vocabulary.careers_departments.yml
  config/sync/taxonomy.vocabulary.careers_years.yml
  config/sync/user.role.contributor.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.caw_careers.yml
  tests/codeception/acceptance/Content/CareerCelebrationsCest.php
Labels: size/l

#9 CAW21-78 Style Sweeteners list and filter view
  composer.json
  config/sync/core.entity_view_display.node.caw_sweetener.stanford_card.yml
  config/sync/core.extension.yml
  config/sync/field_validation.rule_set.config_pages_stanford_basic_site_settings.yml
  config/sync/migrate_plus.migration.caw_sweeteners_components.yml
  config/sync/views.view.caw_careers.yml
  config/sync/views.view.caw_sweeteners.yml
  themes/.gitkeep
  themes/caw_theme/caw_theme.libraries.yml
  themes/caw_theme/caw_theme.theme
  themes/caw_theme/dist/css/sweeteners.views.css
  themes/caw_theme/lib/scss/component/sweeteners/sweeteners.views.scss
  themes/caw_theme/templates/view/views-view--caw-sweeteners--grid-all.html.twig
  themes/caw_theme/yarn.lock
Labels: size/xl

#11 Added media category for easily filtering images
  config/sync/core.entity_form_display.media.image.default.yml
  config/sync/core.entity_form_display.media.image.media_library.yml
  config/sync/core.entity_view_display.media.image.default.yml
  config/sync/core.entity_view_display.media.image.media_library.yml
  config/sync/core.entity_view_display.media.image.stanford_image_large.yml
  config/sync/core.entity_view_display.media.image.stanford_image_large_square.yml
  config/sync/core.entity_view_display.media.image.stanford_image_medium.yml
  config/sync/core.entity_view_display.media.image.stanford_image_medium_square.yml
  config/sync/core.entity_view_display.media.image.stanford_image_stanford_circle.yml
  config/sync/core.entity_view_display.media.image.stanford_image_thumb_square.yml
  config/sync/core.entity_view_display.media.image.thumbnail.yml
  config/sync/field.field.media.image.su_media_category.yml
  config/sync/field.storage.media.su_media_category.yml
  config/sync/filter.format.stanford_limited_html.yml
  config/sync/migrate_plus.migration.caw_careers.yml
  config/sync/migrate_plus.migration.caw_sweeteners.yml
  config/sync/taxonomy.vocabulary.media.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.media.yml
  config/sync/views.view.media_library.yml
Labels: size/s
