Repository SU-SWS/caw_profile, pull requests merged in 2021-09, with the labels that each got.

#13 CAW21-47 Add FontAwesome module for icons support in cards
  composer.json
  config/sync/core.entity_form_display.paragraph.stanford_card.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_card.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_card.variant_1.yml
  config/sync/core.entity_view_display.paragraph.stanford_card.variant_2.yml
  config/sync/core.extension.yml
  config/sync/field.field.paragraph.stanford_card.su_card_icon.yml
  config/sync/field.storage.paragraph.su_card_icon.yml
  config/sync/fontawesome.settings.yml
  modules/caw_profile_helper/caw_profile_helper.libraries.yml
  modules/caw_profile_helper/caw_profile_helper.module
  modules/caw_profile_helper/css/caw_profile_helper.admin.css
  modules/caw_profile_helper/css/layouts/caw_layouts.css
  modules/caw_profile_helper/css/layouts/three_column.css
  modules/caw_profile_helper/css/layouts/two_column.css
  modules/caw_profile_helper/styles/.browserslistrc
  modules/caw_profile_helper/styles/.eslintrc
  modules/caw_profile_helper/styles/.nvmrc
  modules/caw_profile_helper/styles/.sass-lint.yml
  modules/caw_profile_helper/styles/dist/css/caw_profile_helper.admin.css
  modules/caw_profile_helper/styles/dist/css/components/patterns.card.css
  modules/caw_profile_helper/styles/dist/css/layouts/caw_layouts.css
  modules/caw_profile_helper/styles/dist/css/layouts/three_column.css
  modules/caw_profile_helper/styles/dist/css/layouts/two_column.css
  modules/caw_profile_helper/styles/lib/caw_profile_helper.admin.scss
  modules/caw_profile_helper/styles/lib/components/patterns.card.scss
  modules/caw_profile_helper/styles/lib/layouts/caw_layouts.scss
  modules/caw_profile_helper/styles/lib/layouts/three_column.scss
  modules/caw_profile_helper/styles/lib/layouts/two_column.scss
  modules/caw_profile_helper/styles/package-lock.json
  modules/caw_profile_helper/styles/package.json
  modules/caw_profile_helper/styles/webpack.config.js
  modules/caw_profile_helper/styles/yarn.lock
  tests/codeception/functional/Paragraphs/CardCest.php
Labels: size/xl

#14 Create FAQ paragraph with accordion lists
  config/sync/core.entity_form_display.paragraph.stanford_faq.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_faq.default.yml
  config/sync/field.field.paragraph.stanford_faq.su_faq_description.yml
  config/sync/field.field.paragraph.stanford_faq.su_faq_headline.yml
  config/sync/field.field.paragraph.stanford_faq.su_faq_questions.yml
  config/sync/field.storage.paragraph.su_faq_description.yml
  config/sync/field.storage.paragraph.su_faq_headline.yml
  config/sync/field.storage.paragraph.su_faq_questions.yml
  config/sync/paragraphs.paragraphs_type.stanford_accordion.yml
  config/sync/paragraphs.paragraphs_type.stanford_faq.yml
  tests/codeception/functional/Paragraphs/FAQCest.php
  themes/caw_theme/caw_theme.libraries.yml
  themes/caw_theme/caw_theme.theme
  themes/caw_theme/dist/css/faq.css
  themes/caw_theme/lib/js/components/faq.js
  themes/caw_theme/lib/scss/component/components/faq.scss
Labels: size/s

#19 Updates from stanford_profile
  config/sync/core.extension.yml
  config/sync/editoria11y.settings.yml
  config/sync/page_manager.page_variant.people-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_events_list-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_events_upcoming-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_news_list-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_news_list_terms-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_person_list-layout_builder-0.yml
  config/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_stanford_event_types.yml
  config/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_stanford_news_topics.yml
  config/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_stanford_person_types.yml
  config/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_stanford_publication_topics.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/views.view.stanford_publications.yml
  tests/codeception/acceptance/Content/PublicationsCest.php
Labels: size/s

#20 Update layout paragraphs patch
  composer.json
Labels: size/xs

#22 Updates from stanford_profile
  config/sync/field.field.node.stanford_event.su_event_components.yml
  config/sync/field.field.node.stanford_news.su_news_components.yml
  config/sync/field.field.node.stanford_person.su_person_components.yml
  config/sync/field.field.paragraph_row.node_stanford_page_row.su_page_components.yml
  tests/codeception/functional/Paragraphs/AccordionCest.php
Labels: size/xs

#23 Updates from stanford_profile
  config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
Labels: size/xs
