Repository SU-SWS/caw_profile, pull requests merged in 2022-05, with the labels that each got.

#77 Updated layout builder logic
  composer.json
  modules/caw_profile_helper/caw_profile_helper.module
  modules/caw_profile_helper/templates/patterns-use-wrapper-admin.html.twig
Labels: size/xs

#78 Updates from stanford_profile
  CHANGELOG.md
  caw_profile.services.yml
  config/sync/config_pages.type.stanford_basic_site_settings.yml
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_403.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_404.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_home.yml
  config/sync/field.field.paragraph.stanford_media_caption.su_media_caption_caption.yml
  config/sync/field.storage.config_pages.su_site_403.yml
  config/sync/field.storage.config_pages.su_site_404.yml
  config/sync/field.storage.config_pages.su_site_home.yml
  config/sync/migrate_plus.migration.stanford_course_depts.yml
  config/sync/migrate_plus.migration.stanford_courses.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  config/sync/views.view.stanford_courses.yml
  config/sync/views.view.taxonomy_term_pages.yml
  tests/codeception/acceptance/Content/PersonCest.php
  tests/codeception/acceptance/Contrib/ViewsBulkEditCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterLockupCest.php
  tests/codeception/acceptance/Paragraphs/ListsCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/functional/Contrib/ExtLinkCest.php
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
Labels: size/m

#80 8.4.2
  CHANGELOG.md
  caw_profile.info.yml
  config/sync/views.view.stanford_events.yml
Labels: patch
